# -*- coding: utf-8 -*-
"""18فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xnwhu6oOlBn_dl63voUJ5UVCNP8Bq-_8
"""

def majmoe(t):
  sum=0
  while t!=0:
    sum =t%10
    t//=10
    return sum
    def function(n):
      for l in range (n):
        k=majmoe(i)
        if k==n:
          return k
          return print("not found")