# -*- coding: utf-8 -*-
"""9فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class students:
    def __init__(self,id,name):
      self.id=id
      self.name=name

    def __del__(self):
       print(self.name,"deleted")

    def mean(self,grades):
        return sum(grades) / len(grades)

    def is_mashroot(self,grades):
        if self.name(grades)<12:
            return true
        else:
            return false

    def __str__(self):
       return 'student: {} - {}'.format(self.id,self,name)


student = student(1, "Alice")
grades = [14, 15, 12, 10]
print(student.is_mashoot(grades))
print(student)