# -*- coding: utf-8 -*-
"""فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class person:
  def __init__(self,s,n):
    self.score=s
    self.name=n
    print("hello")
    h=person (56,"hasan")