# -*- coding: utf-8 -*-
"""6فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class A ():
     name="ali"
     age=25

A.name="reza"
print(A.name)

test=A()
test.name="ahmad"
print(test.age)