# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVqvTB_Qr6ftyqWU6ZRPSypzq6Rho1OB
"""

def fanc(a,b):
  p=2*(a+b)
  s=a*b
  print(p,s)
  return(p,s)
  k,m=rect(t1,t2)