# -*- coding: utf-8 -*-
"""فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

import math
class circle ():
  pi=math.pi
  def __init__(self,r=5):
    self.rad=r
    print("circle created")
    def perim(self):
      return 2*pi*self.rad
      def Area(self):
        return pi*self.rad*self.rad
        def __del__(self):
          print("circle deleted")
          return _i


    k=circle(10)
    print(k.perim)
    print(k.Area)
    print(k.pi)
    print(k.rad)
    del k