# -*- coding: utf-8 -*-
"""5فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class triangle ():
  def __init__(self,a,b,c):
    self.a=a
    self.b=b
    self.c=c
    if a<b+c and b<a+c and c<a+b :
     print("triangle created")
    else:
      print("triangle false")
    def perim(self):
      return self.a+self.b+self.c
      def Area(self):
        s=(self.a+self.b+self.c)/2
        return (s*(s-self.a)*(s-self.b)*(s-self.c))**(0.5)
        def __del__(self):
           print("triangle deleted")
        return _i
    t=triangle(3,4,5)
    print(t.prim())
    print(t.Area())
    del t