# -*- coding: utf-8 -*-
"""7فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class B ():
      def setvar(self,a,b):
        self.x=absc=a*b
        self.y=c