# -*- coding: utf-8 -*-
"""کد های فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVqvTB_Qr6ftyqWU6ZRPSypzq6Rho1OB
"""

def maximum100():
   a=input()
   a=int(a)
   max=a
   for i in range(99):
     a=int(input())
     if a>max:
        max=a
        return max