# -*- coding: utf-8 -*-
"""فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class person:
  name=None
  score=100
  def say_hello(self):
    print("hello")

