# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNLP-RxbYSOSa9o11P86Ie0xr-rr8KxE
"""

def fanc1():
  print()
  print("salam")
  fanc1()
  fanc1()
  print("khodafezz")