# -*- coding: utf-8 -*-
"""8فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DdLdZQhhKh_mfkjDGmXD5qgJ-A1381
"""

class x:
    def A(self):
        pass
    def B(self):
        pass
    def AC(cls):
        pass