# -*- coding: utf-8 -*-
"""کد های فاطمه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVqvTB_Qr6ftyqWU6ZRPSypzq6Rho1OB
"""

def maximum3(a,b,c):
  max=a
  if b>max:
   max=b
  if c>max:
   max=c
   return max